# Generated by Django 5.1.7 on 2025-04-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='write',
            new_name='writer',
        ),
    ]
